none:

test:
	cd experiments/basic; make test
	cd experiments/backtracking; make test
	cd experiments/nonground; make test
	cd experiments/bidirectional; make test
	cd experiments/optimized; make test

