all:
	echo main | ghci Examples/Company/Baseline.hs
	echo main | ghci Examples/Company/Default.hs
	echo main | ghci Examples/Company/Fallibility.hs
	echo main | ghci Examples/Company/Cflow.hs
	echo main | ghci Examples/Company/Typecase.hs
	echo main | ghci Examples/Company/Reachability.hs
